name: learn-to-sim3
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - astunparse=1.6.3
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - blas=1.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.14
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - contourpy=1.3.1
  - cuda-crt-tools=12.6.85
  - cuda-cudart=12.6.77
  - cuda-cudart_linux-64=12.6.77
  - cuda-cupti=12.6.80
  - cuda-nvcc-tools=12.6.85
  - cuda-nvrtc=12.6.85
  - cuda-nvtx=12.6.77
  - cuda-nvvm-tools=12.6.85
  - cuda-version=12.6
  - cudnn=9.1.1.17
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.6.4
  - flatbuffers=24.3.25
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.10.4
  - gast=0.6.0
  - gcc_impl_linux-64=13.3.0
  - gcc_linux-64=13.3.0
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - google-pasta=0.2.0
  - grpcio=1.62.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gxx_impl_linux-64=13.3.0
  - gxx_linux-64=13.3.0
  - h2=4.1.0
  - h5py=3.12.1
  - hdf5=1.12.1
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - joblib=1.4.2
  - jpeg=9e
  - keras=3.7.0
  - kernel-headers_linux-64=3.10.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.6.4.1
  - libcufft=11.3.0.4
  - libcups=2.4.2
  - libcurand=10.3.7.77
  - libcurl=8.11.1
  - libcusolver=11.7.1.2
  - libcusparse=12.5.4.2
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-devel_linux-64=13.3.0
  - libgcc-ng=14.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnvjitlink=12.6.85
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - libsanitizer=13.3.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=13.3.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.3
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mdurl=0.1.2
  - ml_dtypes=0.4.0
  - munkres=1.1.4
  - mysql=8.4.0
  - namex=0.0.8
  - nccl=2.23.4.1
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.4
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.4.0
  - opt_einsum=3.4.0
  - optree=0.13.1
  - packaging=24.2
  - pcre2=10.42
  - pillow=11.0.0
  - pip=24.2
  - ply=3.11
  - protobuf=4.25.3
  - pycparser=2.22
  - pygments=2.18.0
  - pyparsing=3.2.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=24.3.25
  - python_abi=3.11
  - qt-main=5.15.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - rich=13.9.4
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - sysroot_linux-64=2.17
  - tabulate=0.9.0
  - tensorboard=2.17.1
  - tensorboard-data-server=0.7.0
  - tensorflow=2.17.0
  - tensorflow-base=2.17.0
  - tensorflow-estimator=2.17.0
  - termcolor=2.5.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - werkzeug=3.1.3
  - wheel=0.44.0
  - wrapt=1.17.0
  - xz=5.4.6
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - --find-links https://data.pyg.org/whl/torch-2.5.1+cu124.html
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - attrs==24.3.0
      - filelock==3.13.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - jinja2==3.1.3
      - mpmath==1.3.0
      - multidict==6.1.0
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - propcache==0.2.1
      - psutil==6.1.1
      - sympy==1.13.1
      - torch==2.5.1+cu124
      - torch-cluster==1.6.3+pt25cu124
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt25cu124
      - torch-sparse==0.6.18+pt25cu124
      - torch-spline-conv==1.2.2+pt25cu124
      - torchaudio==2.5.1+cu124
      - torchvision==0.20.1+cu124
      - tqdm==4.67.1
      - triton==3.1.0
      - yarl==1.18.3
