name: learn-to-sim2

channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch-cuda=12.4
  - pytorch
  - torchvision
  - torchaudio
  - pyg
  - torch-scatter
  - scikit-learn
  - numpy
  - tabulate
  - pip
  - pip:
    - matplotlib
    - tensorflow

variables:
  CONDA_PINNED_PACKAGES:
    - pytorch
    - torchaudio
    - torchvision
    - pytorch-cuda=12.4