name: learn-to-sim
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - matplotlib==3.9.3
  - numpy==1.24.0
  - scikit-learn==1.6.0
  - scipy==1.9.3
  - tensorflow==2.17.0
  - pytorch=2.5.0
  - torchvision=0.20.0
  - torchaudio=2.5.0
  - pytorch-cuda=12.4
  - pip
  - pip:
    - texttable==1.7.0
    - torch-geometric==2.6.1
    - torch-scatter==2.1.2
    - torch-sparse==0.6.18