name: learn-to-sim
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - matplotlib==3.9.3
  - numpy==2.2.0
  - scikit-learn==1.6.0
  - scipy==1.14.1
  - sympy==1.13.1
  - tensorflow==2.17.0
  - pytorch=2.5.0
  - torchvision=0.20.0
  - torchaudio=2.5.0
  - pytorch-cuda=12.4
  - pip
  - pip:
    - texttable==1.7.0
    - torch-scatter==2.1.2
    - torch-sparse==0.6.18
    - torch-geometric==2.6.1
